### ISSUE TITLE
RangeError: Invalid typed array length

### ISSUE THREAD

**Issue by dragonjet** [foliojs/unicode-trie#9]
Error when using `pdfkit`, with dependencies towards `fontkit`, then `unicode-trie`

Node version: `6.11.3`

```
{"message":"uncaughtException","stack":"RangeError: Invalid typed array length
    at new Uint8Array (native)
    at new UnicodeTrie (/var/app/current/node_modules/unicode-properties/node_modules/unicode-trie/index.js:87:28)
    at Object.<anonymous> (/var/app/current/node_modules/unicode-properties/unicode-properties.cjs.js:139:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/app/current/node_modules/fontkit/index.js:24:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)","level":"error","timestamp":"2019-11-17T21:45:45.022Z"}
```

**Comment by devongovett** [comment]
Does it work on a newer version of Node? Node 6 is out of support already, and soon even Node 8 will be as well. See https://github.com/nodejs/Release

**Comment by yayajacky** [comment]
It's breaking on v10.17.0.

RangeError: Invalid typed array length: 4034658560
    at new Uint8Array (<anonymous>)
    at new UnicodeTrie (/Users/jack/vynca/code/vynca-session-management-service/node_modules/unicode-properties/node_modules/unicode-trie/index.js:87:28)
    at Object.<anonymous> (/Users/jack/vynca/code/vynca-session-management-service/node_modules/unicode-properties/unicode-properties.cjs.js:139:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/jack/vynca/code/vynca-session-management-service/node_modules/fontkit/index.js:24:31)

**Comment by devongovett** [comment]
What versions of unicode-properties, and unicode-trie do you have?

**Comment by yayajacky** [comment]
unicode-properties: 1.3.0
unicode-trie: 1.0.1

Thanks

**Comment by yayajacky** [comment]
I am using npm resolution to install unicode-trie: 1.0.0 at the moment until this is resolved, thanks

**Comment by devongovett** [comment]
I've unpublished unicode-trie@1.0.1. It contained unintentional breaking changes due to endianness fixes. Working on publishing 2.0.0 instead, and updating unicode-properties to that version. Sorry for the mistake.

**Comment by yayajacky** [comment]
No worries, thanks for the quick response

**Comment by devongovett** [comment]
Ok, unicode-trie@2.0.0 and unicode-properties@1.3.1 are out with the fixes. Thanks for reporting this!
